package com.meiling.common.constant

object ARouteConstants {

    const val LOGIN_ACTIVITY = "/app/LoginActivity"
    const val HOME_ACTIVITY = "/app/HomeActivity"
    const val ACTIVITY_SCAN = "/app/ScanActivity"
    const val ACTIVITY_WEB = "/app/WebActivity"
    const val ACTIVITY_ME_INFO = "/app/MeInfoActivity"
    const val ACTIVITY_SETTING = "/app/SettingActivity"
    const val ACTIVITY_PERMISSIONS = "/app/PermissionsActivity"
    const val FRAGMENT_ME = "/app/MeFragment"
    const val FRAGMENT_GROUP = "/app/GroupFragment"
    const val FRAGMENT_INDEX = "/app/IndexFragment"
    const val FRAGMENT_MARKET = "/app/MarketFragment"
    const val FRAGMENT_MARKET_ITEM = "/app/MarketItemFragment"
    const val FRAGMENT_FOLLOW = "/app/FollowFragment"
    const val FRAGMENT_EXPLORE = "/app/ExploreFragment"
    const val ACTIVITY_ISSUE = "/app/IssueActivity"
    const val ACTIVITY_UPLOAD = "/app/UploadActivity"
    const val ACTIVITY_PREVIEW_IMAGW = "/app/ImagePreviewActivity"
    const val ACTIVITY_PREVIEW_VIDEO = "/app/VideoPreviewActivity"
    const val FRAGMENT_WORKS = "/app/WorksFragment"
    const val FRAGMENT_COLLECTION = "/app/CollectionFragment"
    const val ACTIVITY_SEARCH = "/app/SearchActivity"
    const val ACTIVITY_FOLLOW = "/app/FollowActivity"
    const val ACTIVITY_FANS = "/app/FansActivity"
    const val ACTIVITY_PROFIT = "/app/ProfitActivity"
    const val ACTIVITY_RELEASE_RECORD = "/app/ReleaseRecordActivity"
    const val ACTIVITY_TRANSACTION = "/app/TransactionActivity"
    const val ACTIVITY_WALLET = "/app/WalletActivity"
    const val ACTIVITY_FOLLOW_WORKS = "/app/FollowWorksActivity"
    const val FRAGMENT_RESALE_RECORD = "/app/ResaleRecordFragment"
    const val FRAGMENT_ORDER_RECORD = "/app/OrderRecordFragment"
    const val ACTIVITY_QRCODE = "/app/QRCodeActivity"
    const val ACTIVITY_CHAT_DETAIL = "/app/ChatDetailActivity"
    const val ACTIVITY_REAL_NAME = "/app/RealNameActivity"

}